In [1]:
from torchvision import datasets
data_path = '../temp'
c10 = datasets.CIFAR10(data_path, train=True, download=True)
c10_val = datasets.CIFAR10(data_path, train=False, download=True)

Files already downloaded and verified
Files already downloaded and verified


In [3]:
len(c10)

50000

In [4]:
from torchvision import transforms
to_tensor = transforms.ToTensor()

In [5]:
label_map = {0: 0, 2: 1}
c2 = [(to_tensor(img), label_map[label])
                 for img, label in c10
                 if label in [0, 2]]
c2_val = [(to_tensor(img), label_map[label])
                 for img, label in c10_val
                 if label in [0, 2]]

In [6]:
len(c2)

10000

In [7]:
len(c2_val)

2000

In [10]:
import torch
i = torch.stack([img[0].view(-1).unsqueeze(0) for img in c2]).squeeze(1)

In [53]:
import torch.nn as nn
model = nn.Sequential(
            nn.Linear(3072, 512),
            nn.ReLU(),
            nn.Linear(512, 2))

In [11]:
i.shape

torch.Size([10000, 3072])

In [12]:
v = torch.stack([img[0].view(-1).unsqueeze(0) for img in c2_val]).squeeze(1)

In [13]:
v.shape

torch.Size([2000, 3072])

In [14]:
yt = []
for img in c2:
    label = img[1]
    if label == 0:
        yt.append(torch.tensor([[1.0,0.0]]))
    else:
        yt.append(torch.tensor([[0.0,1.0]]))

In [15]:
y = torch.stack(yt).squeeze(1)

In [16]:
y.shape

torch.Size([10000, 2])

In [17]:
y[0]

tensor([0., 1.])

In [18]:
r = torch.tensor([img[1] for img in c2_val])

In [21]:
r

tensor([0, 0, 0,  ..., 0, 1, 0])

In [24]:
def ev():
    pred = model(v)
    _, p = torch.max(pred, dim=1)
    return int((r == p).sum())/2000

## loss = nn.CrossEntropyLoss()
trainer = torch.optim.SGD(model.parameters(), lr=0.01)
for epoch in range(1000):
    pred = model(i)
    
    l = loss(pred, labels)
    
    trainer.zero_grad()
    l.backward()
    trainer.step()
    
    if epoch%10 == 0:
        print(f'epoch {epoch+1}, loss {l:f}', 'val', ev())

In [55]:
labels = torch.tensor([img[1] for img in c2])

In [49]:
x = torch.tensor([5.1, 1.2, -1.5])
y = torch.tanh(x)
print(y)

tensor([ 0.9999,  0.8337, -0.9051])


In [68]:
import math
value = math.exp(-0.272)
print(value)

0.7618542610898376


In [69]:
2000 * 0.84

1680.0