In [1]:
import torch

In [2]:
x = torch.tensor(5)

In [3]:
y = torch.tensor(3)

In [4]:
x + y

tensor(8)

In [5]:
type(x)

torch.Tensor

In [7]:
x = torch.arange(4)

In [8]:
x

tensor([0, 1, 2, 3])

In [9]:
torch.arange??

Docstring:
arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
with values from the interval ``[start, end)`` taken with common difference
:attr:`step` beginning from `start`.

Note that non-integer :attr:`step` is subject to floating point rounding errors when
comparing against :attr:`end`; to avoid inconsistency, we advise adding a small epsilon to :attr:`end`
in such cases.

.. math::
    \text{out}_{{i+1}} = \text{out}_{i} + \text{step}

Args:
    start (Number): the starting value for the set of points. Default: ``0``.
    end (Number): the ending value for the set of points
    step (Number): the gap between each pair of adjacent points. Default: ``1``.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
       

In [10]:
x[1]

tensor(1)

In [12]:
type(x)

torch.Tensor

In [13]:
type(x[1])

torch.Tensor

In [14]:
len(x)

4

In [16]:
x.shape

torch.Size([4])

In [17]:
x = torch.arange(20)

In [18]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [25]:
x = x.reshape(4,5)

In [26]:
x.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [27]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [28]:
x.dtype

torch.int64

In [2]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [33]:
id(A)

5081816400

In [34]:
B = A.clone()

In [35]:
id(B)

5302189680

In [36]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [37]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [38]:
x.shape

torch.Size([4, 5])

In [39]:
x*A

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [40]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [41]:
x.sum()

tensor(190)

In [42]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [43]:
x.sum(axis=0)

tensor([30, 34, 38, 42, 46])

In [44]:
x.sum(axis=1)

tensor([10, 35, 60, 85])

In [3]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [4]:
sum_A = A.sum(axis=1, keepdims=True)

In [6]:
sum_A.shape

torch.Size([5, 1])

In [7]:
A.shape

torch.Size([5, 4])

In [9]:
A.dim()

2

In [11]:
sum_A.dim()

2

In [13]:
A.sum(axis=1).dim()

1

In [16]:
A.numel??

Docstring:
numel() -> int

See :func:`torch.numel`
Type:      builtin_function_or_method


In [15]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [17]:
torch.numel??

Docstring:
numel(input) -> int

Returns the total number of elements in the :attr:`input` tensor.

Args:
    input (Tensor): the input tensor.

Example::

    >>> a = torch.randn(1, 2, 3, 4, 5)
    >>> torch.numel(a)
    120
    >>> a = torch.zeros(4,4)
    >>> torch.numel(a)
    16
Type:      builtin_function_or_method


In [18]:
y = torch.ones(4, dtype = torch.float32)

In [19]:
x = torch.arange(4, dtype = torch.float32)

In [20]:
x

tensor([0., 1., 2., 3.])

In [21]:
y

tensor([1., 1., 1., 1.])

In [22]:
x * y

tensor([0., 1., 2., 3.])

In [23]:
torch.dot(x, y)

tensor(6.)

In [24]:
x.dim()

1

In [25]:
torch.dot(x, y).dim()

0

In [26]:
torch.sum(x*y)

tensor(6.)

In [27]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [28]:
len(A)

5

In [29]:
A.shape

torch.Size([5, 4])

In [30]:
tensor = torch.rand((3, 4, 5))

In [31]:
tensor

tensor([[[0.6460, 0.8970, 0.6691, 0.1676, 0.8005],
         [0.4818, 0.7097, 0.2165, 0.4557, 0.0159],
         [0.4108, 0.1063, 0.7006, 0.9649, 0.4073],
         [0.7471, 0.2625, 0.1437, 0.4692, 0.0688]],

        [[0.2555, 0.0878, 0.5671, 0.7801, 0.7768],
         [0.2667, 0.8647, 0.8104, 0.2149, 0.4553],
         [0.0954, 0.9766, 0.3301, 0.3946, 0.7573],
         [0.0219, 0.0739, 0.6322, 0.4588, 0.2293]],

        [[0.7185, 0.7882, 0.7033, 0.1319, 0.0642],
         [0.5677, 0.6854, 0.9852, 0.6464, 0.2202],
         [0.8318, 0.1401, 0.7452, 0.9016, 0.6231],
         [0.1263, 0.4526, 0.6925, 0.6620, 0.4878]]])

In [33]:
A.size()

torch.Size([5, 4])

In [34]:
tensor.size()

torch.Size([3, 4, 5])

In [35]:
A.shape

torch.Size([5, 4])